import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import { Providers } from "./providers";
import Header from "./header";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thumbnail App",
  description: "Generated by create next app",
  

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en"  suppressHydrationWarning>
       <link rel="icon" href="./favicon.ico" sizes="any" />
        <body className={inter.className}>
        <link rel="icon" href="/icon.jpg" sizes="any" />
        <Providers>
          <Header />
          <div className="container">
          {children}
          </div>
          </Providers>
          <Toaster />
         </body>
         
      </html>
    
  );
}
